include:
  - content
  - assets/css
  
exclude:
  - readme.md
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
  - README.md
  - content/snippets
  - content/posts
  
kramdown:
  input: Kramdown
  hard_wrap: false
  syntax_highlighter: none
  disable_indented_code_blocks: true

# Global variables
base_url: https://github.com/CodeSpanish/pawsAway.2.0/
favicon: "PawsAway.ico"
favicon_apple: "PawsAway_ico.png"
images_path: ./assets/images/
images_posts_path: ../assets/images/posts/
css_path: ./assets/css/styles.css

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-minifier

sass:
  sass_dir: _sass

sass:
  style: compressed