name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install Ruby and Jekyll dependencies
    - name: Setup Ruby and Bundler
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full build-essential zlib1g-dev
        gem install bundler jekyll

    # Install Dart Sass
    - name: Install Dart Sass
      run: gem install sass-embedded

    # Install dependencies and build
    - name: Build the site
      run: |
        bundle install
        jekyll build --future
